-- Daily maintenance cron: invokes /api/cron/maintenance on the app (GDPR account erasure, retention, etc.)
-- Requires Vault secrets (Dashboard → Project Settings → Vault):
--   maintenance_cron_secret  — same value as CRON_SECRET / VERCEL_CRON_SECRET on Vercel
--   app_base_url             — e.g. https://domumatch.com (no trailing slash)
--
-- NOTE: Do NOT run CREATE EXTENSION pg_cron here. This project already has pg_cron enabled
-- (daily matching). Supabase's pg_cron after-create hook fails with "dependent privileges exist"
-- when extension SQL is re-executed.

CREATE SCHEMA IF NOT EXISTS private;

DO $pg_net$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_net') THEN
    CREATE EXTENSION pg_net WITH SCHEMA extensions;
  END IF;
END;
$pg_net$;

CREATE TABLE IF NOT EXISTS private.maintenance_job_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL CHECK (status IN ('running', 'success', 'failed', 'skipped')),
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  finished_at TIMESTAMPTZ,
  http_status INTEGER,
  response_body TEXT,
  error_message TEXT
);

CREATE INDEX IF NOT EXISTS idx_maintenance_job_runs_started_at
  ON private.maintenance_job_runs (started_at DESC);

-- Speed up daily account erasure selection in maintenance cron
CREATE INDEX IF NOT EXISTS idx_dsar_requests_pending_deletion
  ON public.dsar_requests (deletion_scheduled_at)
  WHERE request_type = 'deletion'
    AND status = 'completed'
    AND deletion_completed_at IS NULL
    AND deletion_scheduled_at IS NOT NULL;

ALTER TABLE public.dsar_requests
  ALTER COLUMN deletion_grace_period_days SET DEFAULT 30;

CREATE OR REPLACE FUNCTION private.invoke_maintenance_cron()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions, vault, cron
AS $$
DECLARE
  v_run_id TEXT := format('maintenance_%s', to_char(now(), 'YYYYMMDD_HH24MISS'));
  v_cron_secret TEXT;
  v_app_base_url TEXT;
  v_url TEXT;
  v_request_id BIGINT;
BEGIN
  SELECT decrypted_secret INTO v_cron_secret
  FROM vault.decrypted_secrets
  WHERE name = 'maintenance_cron_secret'
  LIMIT 1;

  SELECT decrypted_secret INTO v_app_base_url
  FROM vault.decrypted_secrets
  WHERE name = 'app_base_url'
  LIMIT 1;

  IF v_cron_secret IS NULL OR v_app_base_url IS NULL THEN
    INSERT INTO private.maintenance_job_runs (run_id, status, finished_at, error_message)
    VALUES (
      v_run_id,
      'skipped',
      NOW(),
      'Vault secrets maintenance_cron_secret and/or app_base_url are not configured'
    );
    RAISE WARNING 'Maintenance cron skipped: configure vault secrets maintenance_cron_secret and app_base_url';
    RETURN;
  END IF;

  v_url := rtrim(v_app_base_url, '/') || '/api/cron/maintenance';

  INSERT INTO private.maintenance_job_runs (run_id, status)
  VALUES (v_run_id, 'running');

  SELECT net.http_get(
    url := v_url,
    headers := jsonb_build_object(
      'Authorization', 'Bearer ' || v_cron_secret,
      'Content-Type', 'application/json'
    ),
    timeout_milliseconds := 300000
  ) INTO v_request_id;

  IF v_request_id IS NULL THEN
    UPDATE private.maintenance_job_runs
    SET
      status = 'failed',
      finished_at = NOW(),
      error_message = 'pg_net failed to queue maintenance HTTP request'
    WHERE run_id = v_run_id;
    RAISE WARNING 'Maintenance cron: pg_net returned NULL request_id for url=%', v_url;
    RETURN;
  END IF;

  UPDATE private.maintenance_job_runs
  SET
    status = 'success',
    finished_at = NOW(),
    response_body = 'pg_net_request_id=' || v_request_id::text
  WHERE run_id = v_run_id;

EXCEPTION
  WHEN OTHERS THEN
    UPDATE private.maintenance_job_runs
    SET
      status = 'failed',
      finished_at = NOW(),
      error_message = left(SQLERRM, 4000)
    WHERE run_id = v_run_id;
    RAISE;
END;
$$;

REVOKE ALL ON FUNCTION private.invoke_maintenance_cron() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION private.invoke_maintenance_cron() TO postgres;

DO $outer$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    IF EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'daily_maintenance') THEN
      PERFORM cron.unschedule('daily_maintenance');
    END IF;

    PERFORM cron.schedule(
      'daily_maintenance',
      '0 2 * * *',
      $$SELECT private.invoke_maintenance_cron();$$
    );
  ELSE
    RAISE NOTICE 'pg_cron not enabled; enable it in Supabase Dashboard, then run: SELECT private.invoke_maintenance_cron();';
  END IF;
END;
$outer$;
