/**
 * Canonical interests for profile selection / matching.
 * Keep labels short, searchable, and roommate-conversation-friendly.
 * Prefer durable activities over fleeting meme names.
 */
export const INTERESTS_LIST = [
  // Academic & campus life
  "Studying",
  "Academic research",
  "Exam preparation",
  "Note-taking",
  "Productivity systems",
  "Time management",
  "Reading academic papers",
  "Online courses",
  "Self-learning",
  "Language learning",
  "Exchange programs",
  "Erasmus life",
  "Study abroad",
  "Internships",
  "Career development",
  "Resume building",
  "Networking",
  "Public speaking",
  "Debate",
  "Case competitions",
  "Hackathons",
  "Student consulting",
  "Student associations",
  "Student governance",
  "Event organizing",
  "Mentorship",
  "Peer tutoring",
  "First-generation student life",
  "International student life",
  "Library study sessions",
  "Group projects",
  "Thesis writing",
  "Research labs",

  // Careers, business & money
  "Entrepreneurship",
  "Startups",
  "Side hustles",
  "Freelancing",
  "E-commerce",
  "Dropshipping",
  "Investing",
  "Stock trading",
  "Crypto",
  "Web3",
  "Financial literacy",
  "Personal finance",
  "Budgeting",
  "Economics",
  "Finance",
  "Accounting",
  "Marketing",
  "Management",
  "Business strategy",
  "Product management",
  "Consulting",
  "Content creator careers",
  "Creator economy",

  // STEM & tech
  "Data analysis",
  "Statistics",
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "Biotechnology",
  "Neuroscience",
  "Computer science",
  "Programming",
  "Software development",
  "Web development",
  "App development",
  "Artificial intelligence",
  "Machine learning",
  "Prompt engineering",
  "AI tools",
  "Generative AI",
  "Cybersecurity",
  "Blockchain development",
  "Game development",
  "UX/UI design",
  "Engineering",
  "Architecture",
  "Urban planning",
  "Robotics",
  "Open-source contributing",
  "No-code tools",
  "Low-code tools",
  "Automation",
  "Notion",
  "Productivity tools",
  "Technology trends",
  "New apps",
  "Tech reviews",
  "Hardware",
  "Gadgets",
  "Smartphones",
  "Laptops",
  "Custom PCs",
  "Smart home setups",
  "3D printing",

  // Society, impact & identity
  "Psychology",
  "Sociology",
  "Philosophy",
  "Political science",
  "Law",
  "International relations",
  "Ethics",
  "Corporate responsibility",
  "Social impact",
  "NGOs",
  "Volunteering",
  "Charity work",
  "Community building",
  "Student activism",
  "Leadership",
  "Climate action",
  "Environmental science",
  "Sustainability",
  "Renewable energy",
  "Environmental activism",
  "Wildlife conservation",
  "Human rights",
  "Social justice",
  "Disability advocacy",
  "Neurodiversity",
  "Mental health advocacy",
  "LGBTQ+ community",
  "Queer spaces",
  "Pride events",
  "Women's empowerment",
  "Men's mental health",
  "Cultural heritage",
  "Diaspora communities",
  "Immigrant communities",
  "Interfaith dialogue",
  "Faith communities",
  "Black culture",
  "African diaspora",
  "Latinx culture",
  "Asian Pacific culture",
  "South Asian culture",
  "Middle Eastern culture",
  "Indigenous cultures",
  "Multicultural living",

  // Fitness & sports
  "Fitness",
  "Gym workouts",
  "Weightlifting",
  "Bodybuilding",
  "CrossFit",
  "Hyrox",
  "Calisthenics",
  "Running",
  "Jogging",
  "Cycling",
  "Swimming",
  "Yoga",
  "Hot yoga",
  "Pilates",
  "Reformer Pilates",
  "Martial arts",
  "Boxing",
  "Kickboxing",
  "Muay Thai",
  "Judo",
  "Karate",
  "Taekwondo",
  "Brazilian jiu-jitsu",
  "Wrestling",
  "Climbing",
  "Bouldering",
  "Hiking",
  "Trail running",
  "Rucking",
  "Outdoor sports",
  "Football (soccer)",
  "Basketball",
  "Volleyball",
  "Tennis",
  "Badminton",
  "Table tennis",
  "Squash",
  "Padel",
  "Pickleball",
  "Rugby",
  "Cricket",
  "Baseball",
  "Ice hockey",
  "Skating",
  "Skateboarding",
  "Roller skating",
  "Ice skating",
  "Skiing",
  "Snowboarding",
  "Surfing",
  "Rowing",
  "Fencing",
  "Archery",
  "Dance fitness",
  "Zumba",
  "Stretching",
  "Mobility training",
  "Cold plunges",
  "Sauna",
  "Walking clubs",
  "Intramural sports",
  "Campus gym",

  // Wellness & lifestyle
  "Wellness",
  "Mental health",
  "Mindfulness",
  "Meditation",
  "Breathwork",
  "Healthy living",
  "Nutrition",
  "Diet planning",
  "Sleep hygiene",
  "Digital detox",
  "Dopamine detox",
  "Soft life",
  "Slow living",
  "Sober curious",
  "Mocktails",
  "Therapy & self-work",
  "Journaling",
  "Reflection",
  "Minimalism",
  "Habit building",
  "Goal setting",
  "Life planning",
  "Personal growth",
  "Self-improvement",
  "Confidence building",
  "Communication skills",
  "Emotional intelligence",
  "Social skills",
  "Dating",
  "Relationships",
  "Public confidence",
  "Personal branding",
  "Online presence",

  // Music
  "Music",
  "Playing instruments",
  "Guitar",
  "Piano",
  "Drums",
  "Violin",
  "Ukulele",
  "Bass guitar",
  "DJing",
  "Music production",
  "Songwriting",
  "Singing",
  "Choir",
  "A cappella",
  "Live performances",
  "Concerts",
  "Music festivals",
  "Electronic music",
  "Hip-hop",
  "Rap",
  "R&B",
  "Jazz",
  "Classical music",
  "Rock",
  "Indie music",
  "Bedroom pop",
  "Hyperpop",
  "Afrobeats",
  "Amapiano",
  "Latin music",
  "Reggaeton",
  "K-pop",
  "J-pop",
  "City pop",
  "Drill music",
  "Phonk",
  "Lo-fi beats",
  "Vinyl collecting",
  "Playlist curating",
  "Sound design",
  "Podcasting",
  "Audio editing",

  // Arts & creative
  "Art",
  "Drawing",
  "Sketching",
  "Painting",
  "Digital art",
  "Illustration",
  "Graphic design",
  "Motion design",
  "Animation",
  "3D modeling",
  "Photography",
  "Film photography",
  "Disposable cameras",
  "Videography",
  "Film making",
  "Cinematography",
  "Video editing",
  "Short-form content creation",
  "YouTube",
  "TikTok",
  "Instagram content",
  "BeReal",
  "Storytelling",
  "Creative writing",
  "Poetry",
  "Spoken word",
  "Blogging",
  "Substack writing",
  "Journalism",
  "Screenwriting",
  "Copywriting",
  "UX writing",
  "Creative coding",
  "Acting",
  "Improv",
  "Theatre",
  "Musical theatre",
  "Stand-up comedy",
  "Open mics",
  "Calligraphy",
  "Lettering",
  "Scrapbooking",
  "Collage art",
  "Pottery",
  "Ceramics",
  "Sculpting",
  "Crochet",
  "Knitting",
  "Embroidery",
  "Cross-stitch",
  "Sewing",
  "Needle felting",
  "Crafting",
  "DIY projects",
  "Jewelry making",
  "Resin art",
  "Candle making",
  "Soap making",

  // Gaming & play
  "Gaming",
  "PC gaming",
  "Console gaming",
  "Mobile gaming",
  "Esports",
  "Competitive gaming",
  "Casual gaming",
  "Cozy games",
  "Indie games",
  "Game streaming",
  "Twitch streaming",
  "Speedrunning",
  "Game modding",
  "Board games",
  "Card games",
  "Chess",
  "Poker",
  "Mahjong",
  "Strategy games",
  "RPGs",
  "Simulation games",
  "Puzzle games",
  "Party games",
  "Dungeons & Dragons",
  "Tabletop RPGs",
  "Warhammer",
  "Miniature painting",
  "Trading card games",
  "Pokémon TCG",
  "Magic: The Gathering",
  "Game design theory",
  "Arcade nights",
  "LAN parties",
  "Discord communities",

  // Travel & outdoors
  "Traveling",
  "Backpacking",
  "Solo travel",
  "Group travel",
  "Cultural exchange",
  "Digital nomad lifestyle",
  "City exploration",
  "Nature exploration",
  "Beach travel",
  "Mountain trips",
  "Road trips",
  "Budget travel",
  "Luxury travel",
  "Hostel life",
  "Travel photography",
  "Travel vlogging",
  "Museum hopping",
  "Gallery visits",
  "National parks",
  "Camping",
  "Glamping",
  "Van life",
  "Weekend getaways",
  "Urban exploration",
  "Photography walks",
  "Birdwatching",
  "Foraging",
  "Gardening",
  "Houseplants",
  "Plant parenting",
  "Nature photography",
  "Stargazing",
  "Picnic culture",
  "Bike touring",
  "City biking",

  // Food & drink
  "Food",
  "Cooking",
  "Baking",
  "Home cooking",
  "Meal prep",
  "Nutrition cooking",
  "Vegan food",
  "Vegetarian food",
  "Halal food",
  "Kosher food",
  "Street food",
  "Fine dining",
  "Café hopping",
  "Coffee brewing",
  "Specialty coffee",
  "Matcha",
  "Tea culture",
  "Bubble tea",
  "Wine tasting",
  "Cocktail making",
  "Mixology",
  "Food photography",
  "Restaurant reviews",
  "Sourdough baking",
  "Air fryer cooking",
  "Protein recipes",
  "Homemade pasta",
  "Dumpling making",
  "BBQ & grilling",
  "Brunch culture",
  "Farmers markets",
  "Food festivals",
  "World cuisines",
  "African cuisine",
  "Caribbean cuisine",
  "East Asian cuisine",
  "South Asian cuisine",
  "Middle Eastern cuisine",
  "Latin American cuisine",
  "Mediterranean cuisine",
  "Southeast Asian cuisine",
  "Fermentation",
  "Hot sauce collecting",

  // Fashion & self-expression
  "Fashion",
  "Streetwear",
  "High fashion",
  "Vintage clothing",
  "Thrifting",
  "Depop shopping",
  "Sustainable fashion",
  "Outfit styling",
  "Grooming",
  "Skincare",
  "Hair styling",
  "Nail art",
  "Makeup",
  "Jewelry",
  "Watches",
  "Sneakers",
  "Sneaker collecting",
  "Fashion content creation",
  "Y2K fashion",
  "Gorpcore",
  "Quiet luxury style",
  "Archive fashion",
  "Cosplay",
  "Costume design",
  "Tattoo culture",
  "Piercings",

  // Social & nightlife
  "Social life",
  "Making friends",
  "Networking events",
  "Parties",
  "House parties",
  "Nightlife",
  "Clubbing",
  "Festivals",
  "Festival camping",
  "Social drinking",
  "Coffee meetups",
  "Study groups",
  "Deep conversations",
  "Philosophy talks",
  "Cultural discussions",
  "Language exchange meetups",
  "Book clubs",
  "Game nights",
  "Movie nights",
  "Potlucks",
  "Roommate dinners",
  "Walking meetups",
  "Run clubs",
  "Dance nights",
  "Karaoke",
  "Trivia nights",
  "Pub quizzes",

  // Media & fandom
  "Media consumption",
  "Movies",
  "Cinema",
  "Film analysis",
  "TV shows",
  "Streaming platforms",
  "Documentaries",
  "Anime",
  "Manga",
  "Comics",
  "Graphic novels",
  "Webtoons",
  "K-dramas",
  "C-dramas",
  "Turkish dramas",
  "Nollywood",
  "Bollywood",
  "Latin American telenovelas",
  "Sci-fi",
  "Fantasy",
  "Romantasy",
  "Mystery",
  "Crime stories",
  "Horror",
  "Romance genres",
  "BookTok",
  "Reading",
  "Physical books",
  "Audiobooks",
  "E-readers",
  "Library runs",
  "Dark academia",
  "Cozy reading",
  "Fan fiction",
  "Fandom culture",
  "Comic conventions",
  "True crime podcasts",
  "Comedy podcasts",
  "Sports watching",
  "Football fandom",
  "Basketball fandom",
  "Formula 1",
  "Olympics",
  "Esports spectating",

  // Culture, faith & ideas
  "Culture",
  "History",
  "World politics",
  "Current affairs",
  "Geopolitics",
  "Cultural studies",
  "Anthropology",
  "Languages",
  "Linguistics",
  "Translation",
  "Multilingualism",
  "National identity",
  "Global cultures",
  "Spirituality",
  "Religion",
  "Philosophy of life",
  "Stoicism",
  "Buddhism",
  "Mind-body connection",
  "Astrology",
  "Astronomy",
  "Space exploration",

  // Practical & collector hobbies
  "Practical skills",
  "Repairing electronics",
  "Woodworking",
  "Home organization",
  "Interior design",
  "Animals",
  "Pet care",
  "Dog training",
  "Cat behavior",
  "Marine life",
  "Aviation",
  "Drones",
  "FPV flying",
  "Cars",
  "Motorsports",
  "Car detailing",
  "Motorcycles",
  "ASMR",
  "Voice acting",
  "Speed reading",
  "Memory techniques",
  "Competitive exams",
  "Trivia",
  "Quiz competitions",
  "Puzzle books",
  "Jigsaw puzzles",
  "Crossword puzzles",
  "Sudoku",
  "Collecting",
  "Stamp collecting",
  "Coin collecting",
  "Blind box collecting",
  "Figurine collecting",
  "Stationery collecting",
  "Fountain pens",
  "Analog hobbies",
  "Letter writing",
  "Snail mail",
  "Polaroids",
  "Film cameras",
  "Record collecting",
] as const

/**
 * Diverse starter suggestions shown when the interests picker opens
 * with an empty search query. Keep this list curated and balanced.
 */
export const FEATURED_INTERESTS = [
  "Music",
  "Cooking",
  "Gym workouts",
  "Reading",
  "Traveling",
  "Movies",
  "Gaming",
  "Photography",
  "Café hopping",
  "Hiking",
  "BookTok",
  "Crochet",
  "Pickleball",
  "Padel",
  "Yoga",
  "K-pop",
  "Anime",
  "Football (soccer)",
  "Thrifting",
  "Podcasting",
  "Volunteering",
  "Language learning",
  "Board games",
  "Dungeons & Dragons",
  "Matcha",
  "Skincare",
  "Concerts",
  "Running",
  "Climbing",
  "Pottery",
  "LGBTQ+ community",
  "International student life",
  "Afrobeats",
  "K-dramas",
  "Halal food",
  "Basketball",
  "Digital art",
  "Study groups",
  "Mental health",
  "Startups",
  "Artificial intelligence",
  "Formula 1",
  "Houseplants",
  "Karaoke",
  "Sourdough baking",
  "Film photography",
  "Queer spaces",
  "Faith communities",
  "Neurodiversity",
  "Cultural heritage",
] as const

export type Interest = typeof INTERESTS_LIST[number]
