export const INTERESTS_LIST = [
  "Studying",
  "Academic research",
  "Exam preparation",
  "Note-taking",
  "Productivity systems",
  "Time management",
  "Reading academic papers",
  "Online courses",
  "Self-learning",
  "Language learning",
  "Exchange programs",
  "Internships",
  "Career development",
  "Resume building",
  "Networking",
  "Public speaking",
  "Debate",
  "Case competitions",
  "Hackathons",
  "Student consulting",
  "Entrepreneurship",
  "Startups",
  "Side hustles",
  "Freelancing",
  "E-commerce",
  "Dropshipping",
  "Investing",
  "Stock trading",
  "Crypto",
  "Web3",
  "Financial literacy",
  "Personal finance",
  "Economics",
  "Finance",
  "Accounting",
  "Marketing",
  "Management",
  "Business strategy",
  "Data analysis",
  "Statistics",
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "Psychology",
  "Sociology",
  "Philosophy",
  "Political science",
  "Law",
  "International relations",
  "Computer science",
  "Programming",
  "Software development",
  "Web development",
  "App development",
  "Artificial intelligence",
  "Machine learning",
  "Cybersecurity",
  "Blockchain development",
  "Game development",
  "UX/UI design",
  "Product management",
  "Engineering",
  "Architecture",
  "Urban planning",
  "Environmental science",
  "Sustainability",
  "Climate action",
  "Renewable energy",
  "Ethics",
  "Corporate responsibility",
  "Social impact",
  "NGOs",
  "Volunteering",
  "Charity work",
  "Community building",
  "Student activism",
  "Leadership",
  "Student governance",
  "Event organizing",
  "Student associations",
  "Mentorship",
  "Peer tutoring",
  "Fitness",
  "Gym workouts",
  "Weightlifting",
  "Bodybuilding",
  "CrossFit",
  "Running",
  "Jogging",
  "Cycling",
  "Swimming",
  "Yoga",
  "Pilates",
  "Calisthenics",
  "Martial arts",
  "Boxing",
  "Kickboxing",
  "Judo",
  "Karate",
  "Taekwondo",
  "Wrestling",
  "Climbing",
  "Hiking",
  "Outdoor sports",
  "Football (soccer)",
  "Basketball",
  "Volleyball",
  "Tennis",
  "Badminton",
  "Table tennis",
  "Squash",
  "Rugby",
  "Cricket",
  "Baseball",
  "Ice hockey",
  "Skating",
  "Skiing",
  "Snowboarding",
  "Surfing",
  "Rowing",
  "Dance fitness",
  "Zumba",
  "Stretching",
  "Mobility training",
  "Wellness",
  "Mental health",
  "Mindfulness",
  "Meditation",
  "Breathwork",
  "Healthy living",
  "Nutrition",
  "Diet planning",
  "Music",
  "Playing instruments",
  "Guitar",
  "Piano",
  "Drums",
  "Violin",
  "DJing",
  "Music production",
  "Songwriting",
  "Singing",
  "Choir",
  "Live performances",
  "Concerts",
  "Music festivals",
  "Electronic music",
  "Hip-hop",
  "Rap",
  "R&B",
  "Jazz",
  "Classical music",
  "Rock",
  "Indie music",
  "Afrobeats",
  "Latin music",
  "K-pop",
  "Sound design",
  "Podcasting",
  "Audio editing",
  "Art",
  "Drawing",
  "Sketching",
  "Painting",
  "Digital art",
  "Illustration",
  "Graphic design",
  "Motion design",
  "Animation",
  "3D modeling",
  "Photography",
  "Videography",
  "Film making",
  "Cinematography",
  "Video editing",
  "Short-form content creation",
  "YouTube",
  "TikTok",
  "Instagram content",
  "Storytelling",
  "Creative writing",
  "Poetry",
  "Blogging",
  "Journalism",
  "Screenwriting",
  "Copywriting",
  "UX writing",
  "Creative coding",
  "Gaming",
  "PC gaming",
  "Console gaming",
  "Mobile gaming",
  "Esports",
  "Competitive gaming",
  "Casual gaming",
  "Game streaming",
  "Twitch streaming",
  "Speedrunning",
  "Game modding",
  "Board games",
  "Card games",
  "Chess",
  "Poker",
  "Strategy games",
  "RPGs",
  "Simulation games",
  "Puzzle games",
  "Game design theory",
  "Traveling",
  "Backpacking",
  "Solo travel",
  "Group travel",
  "Cultural exchange",
  "Digital nomad lifestyle",
  "City exploration",
  "Nature exploration",
  "Beach travel",
  "Mountain trips",
  "Road trips",
  "Budget travel",
  "Luxury travel",
  "Study abroad",
  "Erasmus life",
  "Hostel life",
  "Travel photography",
  "Travel vlogging",
  "Food",
  "Cooking",
  "Baking",
  "Home cooking",
  "Meal prep",
  "Nutrition cooking",
  "Vegan food",
  "Vegetarian food",
  "Street food",
  "Fine dining",
  "Café hopping",
  "Coffee brewing",
  "Specialty coffee",
  "Tea culture",
  "Wine tasting",
  "Cocktail making",
  "Mixology",
  "Food photography",
  "Restaurant reviews",
  "Fashion",
  "Streetwear",
  "High fashion",
  "Vintage clothing",
  "Thrifting",
  "Sustainable fashion",
  "Outfit styling",
  "Personal branding",
  "Grooming",
  "Skincare",
  "Hair styling",
  "Jewelry",
  "Watches",
  "Sneakers",
  "Fashion content creation",
  "Social life",
  "Making friends",
  "Networking events",
  "Parties",
  "Nightlife",
  "Clubbing",
  "Festivals",
  "Social drinking",
  "Coffee meetups",
  "Study groups",
  "Deep conversations",
  "Philosophy talks",
  "Cultural discussions",
  "Language exchange meetups",
  "Personal growth",
  "Self-improvement",
  "Habit building",
  "Goal setting",
  "Life planning",
  "Confidence building",
  "Communication skills",
  "Emotional intelligence",
  "Dating",
  "Relationships",
  "Social skills",
  "Public confidence",
  "Personal branding",
  "Online presence",
  "Technology trends",
  "New apps",
  "Productivity tools",
  "Notion",
  "AI tools",
  "Automation",
  "No-code tools",
  "Low-code tools",
  "Tech reviews",
  "Hardware",
  "Gadgets",
  "Smartphones",
  "Laptops",
  "Custom PCs",
  "Media consumption",
  "Movies",
  "Cinema",
  "Film analysis",
  "TV shows",
  "Streaming platforms",
  "Documentaries",
  "Anime",
  "Manga",
  "Comics",
  "Graphic novels",
  "Sci-fi",
  "Fantasy",
  "Mystery",
  "Crime stories",
  "Horror",
  "Romance genres",
  "Culture",
  "History",
  "World politics",
  "Current affairs",
  "Geopolitics",
  "Cultural studies",
  "Anthropology",
  "Languages",
  "Linguistics",
  "Translation",
  "Multilingualism",
  "National identity",
  "Global cultures",
  "Spirituality",
  "Religion",
  "Philosophy of life",
  "Stoicism",
  "Buddhism",
  "Mind-body connection",
  "Journaling",
  "Reflection",
  "Minimalism",
  "Practical skills",
  "DIY projects",
  "Repairing electronics",
  "Woodworking",
  "3D printing",
  "Sewing",
  "Knitting",
  "Crafting",
  "Home organization",
  "Interior design",
  "Smart home setups",
  "Animals",
  "Pet care",
  "Dog training",
  "Cat behavior",
  "Wildlife conservation",
  "Nature photography",
  "Marine life",
  "Environmental activism",
  "Niche interests",
  "Astrology",
  "Astronomy",
  "Space exploration",
  "Aviation",
  "Drones",
  "FPV flying",
  "Cars",
  "Motorsports",
  "Car detailing",
  "Motorcycles",
  "Urban exploration",
  "Photography walks",
  "ASMR",
  "Voice acting",
  "Speed reading",
  "Memory techniques",
  "Competitive exams",
  "Trivia",
  "Quiz competitions"
] as const

export type Interest = typeof INTERESTS_LIST[number]

