-- Database-native daily matching orchestration using pg_cron.
-- This shifts the heavy matching loop into Postgres (no Vercel timeouts),
-- with idempotent upserts and run logging for observability.

-- 1) Ensure pg_cron is available.
-- Supabase requires pg_cron installed in `pg_catalog` and uses the `cron` schema for jobs.
CREATE EXTENSION IF NOT EXISTS pg_cron WITH SCHEMA pg_catalog;

-- Ensure the `postgres` role can manage cron metadata.
GRANT USAGE ON SCHEMA cron TO postgres;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA cron TO postgres;

-- 2) Private schema for job orchestration + logs (not exposed via PostgREST).
CREATE SCHEMA IF NOT EXISTS private;

-- 3) Run log table (private; queryable by service/admin clients via SQL).
CREATE TABLE IF NOT EXISTS private.matching_job_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id TEXT NOT NULL UNIQUE,
  job_name TEXT NOT NULL DEFAULT 'daily_matching',
  user_type TEXT,
  status TEXT NOT NULL CHECK (status IN ('running', 'success', 'failed', 'skipped')),
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  finished_at TIMESTAMPTZ,
  processed_users INTEGER NOT NULL DEFAULT 0,
  suggestions_upserted INTEGER NOT NULL DEFAULT 0,
  error_message TEXT,
  error_detail JSONB
);

CREATE INDEX IF NOT EXISTS idx_matching_job_runs_started_at
  ON private.matching_job_runs (started_at DESC);

-- 4) Idempotency for pair suggestions.
-- We add normalized pair columns + a unique index, so the DB job can upsert safely.
ALTER TABLE public.match_suggestions
  ADD COLUMN IF NOT EXISTS user_low_id UUID,
  ADD COLUMN IF NOT EXISTS user_high_id UUID;

-- Backfill for existing pair suggestions (safe to re-run).
UPDATE public.match_suggestions ms
SET
  user_low_id = LEAST(ms.member_ids[1], ms.member_ids[2]),
  user_high_id = GREATEST(ms.member_ids[1], ms.member_ids[2])
WHERE ms.kind = 'pair'
  AND ms.user_low_id IS NULL
  AND ms.user_high_id IS NULL
  AND array_length(ms.member_ids, 1) = 2;

-- Maintain normalized pair columns automatically.
CREATE OR REPLACE FUNCTION public.set_match_suggestions_pair_users()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.kind = 'pair' AND array_length(NEW.member_ids, 1) = 2 THEN
    NEW.user_low_id := LEAST(NEW.member_ids[1], NEW.member_ids[2]);
    NEW.user_high_id := GREATEST(NEW.member_ids[1], NEW.member_ids[2]);
  ELSE
    NEW.user_low_id := NULL;
    NEW.user_high_id := NULL;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_set_match_suggestions_pair_users ON public.match_suggestions;
CREATE TRIGGER trg_set_match_suggestions_pair_users
  BEFORE INSERT OR UPDATE OF kind, member_ids
  ON public.match_suggestions
  FOR EACH ROW
  EXECUTE FUNCTION public.set_match_suggestions_pair_users();

-- Deduplicate existing pair rows before enforcing uniqueness.
-- Keep ONE row per (user_low_id, user_high_id), preferring:
--   1) terminal statuses (confirmed > accepted > pending > declined > expired)
--   2) newest created_at
--   3) highest fit_index
WITH ranked AS (
  SELECT
    ms.id,
    ms.user_low_id,
    ms.user_high_id,
    ROW_NUMBER() OVER (
      PARTITION BY ms.user_low_id, ms.user_high_id
      ORDER BY
        CASE ms.status
          WHEN 'confirmed' THEN 5
          WHEN 'accepted' THEN 4
          WHEN 'pending' THEN 3
          WHEN 'declined' THEN 2
          WHEN 'expired' THEN 1
          ELSE 0
        END DESC,
        ms.created_at DESC NULLS LAST,
        ms.fit_index DESC NULLS LAST
    ) AS rn
  FROM public.match_suggestions ms
  WHERE ms.kind = 'pair'
    AND ms.user_low_id IS NOT NULL
    AND ms.user_high_id IS NOT NULL
)
DELETE FROM public.match_suggestions ms
USING ranked r
WHERE ms.id = r.id
  AND r.rn > 1;

-- Unique pair constraint for upserts (only for pair-kind rows).
CREATE UNIQUE INDEX IF NOT EXISTS uq_match_suggestions_pair
  ON public.match_suggestions (user_low_id, user_high_id)
  WHERE kind = 'pair';

-- 5) Stored procedure that runs the daily matching loop in batches.
-- Uses an advisory lock to prevent concurrent runs.
CREATE OR REPLACE PROCEDURE private.run_daily_matching(
  p_user_type TEXT,
  p_batch_size INTEGER DEFAULT 250,
  p_top_n INTEGER DEFAULT 10,
  p_min_score NUMERIC DEFAULT 0.60,
  p_auto_accept_fit_index INTEGER DEFAULT 80
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = private, public, extensions, pg_catalog
AS $$
DECLARE
  v_lock_acquired BOOLEAN;
  v_run_id TEXT := format('pg_cron_%s_%s', coalesce(p_user_type, 'unknown'), to_char(now(), 'YYYYMMDD_HH24MISS'));
  v_processed_users INTEGER := 0;
  v_upserts INTEGER := 0;
  v_user_id UUID;
  v_last_user_id UUID := '00000000-0000-0000-0000-000000000000';
  v_batch_count INTEGER := 0;
  v_match RECORD;
  v_fit_index INTEGER;
  v_status TEXT;
  v_member_ids UUID[];
  v_low UUID;
  v_high UUID;
BEGIN
  -- Prevent overlapping runs (e.g., manual call during scheduled run).
  v_lock_acquired := pg_try_advisory_lock(hashtext('private.run_daily_matching'));

  IF NOT v_lock_acquired THEN
    INSERT INTO private.matching_job_runs (run_id, user_type, status, error_message)
    VALUES (v_run_id, p_user_type, 'skipped', 'Another matching run is already in progress');
    RETURN;
  END IF;

  INSERT INTO private.matching_job_runs (run_id, user_type, status)
  VALUES (v_run_id, p_user_type, 'running');

  -- Batch loop. We keep transactions short by committing per batch.
  LOOP
    -- Start a new transaction for each batch to reduce long-running locks.
    START TRANSACTION;

    v_batch_count := 0;

    FOR v_user_id IN
      SELECT u.id
      FROM public.users u
      JOIN public.profiles p ON p.user_id = u.id
      WHERE u.is_active = TRUE
        AND p.verification_status = 'verified'
        AND p.user_type = p_user_type
        AND u.id > v_last_user_id
      ORDER BY u.id
      LIMIT p_batch_size
    LOOP
      v_processed_users := v_processed_users + 1;
      v_batch_count := v_batch_count + 1;
      v_last_user_id := v_user_id;

      -- For each user, find top matches using the existing hybrid DB function.
      FOR v_match IN
        SELECT *
        FROM public.find_best_matches_v2(v_user_id, p_top_n, 200, p_min_score)
      LOOP
        -- Normalize pair order
        v_low := LEAST(v_user_id, v_match.user_id);
        v_high := GREATEST(v_user_id, v_match.user_id);
        v_member_ids := ARRAY[v_low, v_high];

        v_fit_index := GREATEST(0, LEAST(100, ROUND((v_match.compatibility_score::numeric) * 100)::int));
        v_status := CASE WHEN v_fit_index >= p_auto_accept_fit_index THEN 'accepted' ELSE 'pending' END;

        INSERT INTO public.match_suggestions (
          run_id,
          kind,
          member_ids,
          fit_score,
          fit_index,
          section_scores,
          reasons,
          expires_at,
          status,
          accepted_by
        )
        VALUES (
          v_run_id,
          'pair',
          v_member_ids,
          v_match.compatibility_score,
          v_fit_index,
          jsonb_build_object(
            'academic_bonus', v_match.academic_bonus,
            'top_alignment', v_match.top_alignment,
            'watch_out', v_match.watch_out,
            'algo', 'pg_cron_hybrid_v2'
          ),
          ARRAY[COALESCE(v_match.top_alignment, 'Good overall compatibility')],
          NOW() + INTERVAL '100 years',
          v_status,
          ARRAY[]::uuid[]
        )
        ON CONFLICT (user_low_id, user_high_id)
        DO UPDATE SET
          run_id = EXCLUDED.run_id,
          member_ids = EXCLUDED.member_ids,
          fit_score = EXCLUDED.fit_score,
          fit_index = EXCLUDED.fit_index,
          section_scores = EXCLUDED.section_scores,
          reasons = EXCLUDED.reasons,
          expires_at = EXCLUDED.expires_at,
          -- Never overwrite terminal states:
          status = CASE
            WHEN public.match_suggestions.status IN ('confirmed', 'declined') THEN public.match_suggestions.status
            ELSE EXCLUDED.status
          END,
          updated_at = NOW();

        v_upserts := v_upserts + 1;
      END LOOP;
    END LOOP;

    COMMIT;

    -- Exit when we processed zero users in this batch.
    EXIT WHEN v_batch_count = 0;
  END LOOP;

  UPDATE private.matching_job_runs
  SET
    status = 'success',
    processed_users = v_processed_users,
    suggestions_upserted = v_upserts,
    finished_at = NOW()
  WHERE run_id = v_run_id;

  PERFORM pg_advisory_unlock(hashtext('private.run_daily_matching'));
EXCEPTION
  WHEN OTHERS THEN
    -- Ensure any open transaction is closed before logging failure.
    BEGIN
      ROLLBACK;
    EXCEPTION
      WHEN OTHERS THEN
        -- ignore rollback errors
        NULL;
    END;

    UPDATE private.matching_job_runs
    SET
      status = 'failed',
      finished_at = NOW(),
      processed_users = v_processed_users,
      suggestions_upserted = v_upserts,
      error_message = SQLERRM,
      error_detail = jsonb_build_object('sqlstate', SQLSTATE, 'run_id', v_run_id)
    WHERE run_id = v_run_id;

    PERFORM pg_advisory_unlock(hashtext('private.run_daily_matching'));
    RAISE;
END;
$$;

-- 6) Schedule daily runs inside the database.
-- Note: We create schedules only if they don't already exist (idempotent).
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'daily_matching_students') THEN
    PERFORM cron.schedule(
      'daily_matching_students',
      '0 2 * * *',
      $cmd$CALL private.run_daily_matching('student');$cmd$
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'daily_matching_professionals') THEN
    PERFORM cron.schedule(
      'daily_matching_professionals',
      '10 2 * * *',
      $cmd$CALL private.run_daily_matching('professional');$cmd$
    );
  END IF;
END $$;

